### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Read Dataset

In [2]:
df = pd.read_csv('Order_Items_v2.csv')
df.head()

,order_item_id,order_id,product_id,quantity,unit_price,discount,returned_flag,batch_reference
0,1,37408,5628,6,98.48,22.15,No,BATCH-JNW2X8A7
1,2,20682,9300,8,1087.17,0.37,No,BATCH-PISPIUZM
2,3,15639,11947,6,838.90,30.48,No,BATCH-6BMNNTJX
3,4,14324,7718,4,1390.89,33.83,No,BATCH-01VYK1IT
4,5,31716,5116,5,538.63,22.62,No,BATCH-UO8SHE4N

In [3]:
df.shape

(91564, 8)

### Data Cleaning

#### Checking Missing Values

In [4]:
df.isnull().sum()

order_item_id      0
order_id           0
product_id         0
quantity           0
unit_price         0
discount           0
returned_flag      0
batch_reference    0
dtype: int64

#### Checking Duplicates

In [5]:
df.duplicated().sum()  #0.7%

np.int64(726)

#### Removing Duplicates

In [6]:
df = df.drop_duplicates()

In [7]:
df.duplicated().sum()

np.int64(0)

#### Checking Data Types

In [8]:
df.dtypes

order_item_id        int64
order_id             int64
product_id           int64
quantity             int64
unit_price         float64
discount           float64
returned_flag       object
batch_reference     object
dtype: object

#### Detecting Outliers

In [9]:
cols = ['quantity','unit_price','discount']
a = df[cols].describe(percentiles=[0.01,0.02,0.05,0.95,0.97,0.98,0.99]).T
a = a.iloc[:,3:]
a

,min,1%,2%,5%,50%,95%,97%,98%,99%,max
quantity,-5.00,1.0000,1.000,1.00,4.000,8.00,8.0000,8.00,8.0000,8.00
unit_price,-499.93,17.4937,32.397,78.17,749.985,1424.51,1455.4389,1471.40,1486.2763,1499.99
discount,0.00,0.4000,0.800,1.98,20.010,38.09,38.8800,39.27,39.6800,179.96

#### Handling Outliers

In [10]:
print((df['discount']>40).sum())
print((df['unit_price'] < 0).sum())
print((df['quantity'] < 0).sum())

183
183
272

In [11]:
a = ['quantity','unit_price']
for i in a:
    lower = df[i].quantile(0.01)
    df[i] = np.where(df[i]<lower,lower,df[i])

In [12]:
df['discount'] = np.where(df['discount']>df['discount'].quantile(0.99),df['discount'].quantile(0.99),df['discount'])

In [13]:
cols = ['quantity','unit_price','discount']
a = df[cols].describe(percentiles=[0.01,0.02,0.05,0.95,0.97,0.98,0.99]).T
a = a.iloc[:,3:]
a

,min,1%,2%,5%,50%,95%,97%,98%,99%,max
quantity,1.0000,1.000000,1.000,1.00,4.000,8.00,8.0000,8.00,8.0000,8.00
unit_price,17.4937,17.496031,32.397,78.17,749.985,1424.51,1455.4389,1471.40,1486.2763,1499.99
discount,0.0000,0.400000,0.800,1.98,20.010,38.09,38.8800,39.27,39.6800,39.68

#### Removing Irrelevent Column

In [14]:
df.drop(columns='batch_reference',inplace=True)

In [15]:
df.columns

Index(['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price',
       'discount', 'returned_flag'],
      dtype='object')

In [16]:
df.head()

,order_item_id,order_id,product_id,quantity,unit_price,discount,returned_flag
0,1,37408,5628,6.0,98.48,22.15,No
1,2,20682,9300,8.0,1087.17,0.37,No
2,3,15639,11947,6.0,838.90,30.48,No
3,4,14324,7718,4.0,1390.89,33.83,No
4,5,31716,5116,5.0,538.63,22.62,No

In [17]:
df.shape

(90838, 7)

#### Saving Cleaned Dataset

In [18]:
df.to_csv('Orders_Items_clean.csv',index=False)