### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Read Dataset

In [2]:
df = pd.read_csv('Orders_v2.csv')
df.head()

,order_id,customer_id,order_date,warehouse_id,order_status,shipment_status,payment_method,shipping_mode,session_id
0,1,120024,14/02/2024,8450,Processing,Returned,UPI,Same Day,SID-HXbWNdbIsuSV
1,2,204325,23/12/2024,7713,Delivered,Not Shipped,Credit Card,Express,SID-CRMAuBSjK2LC
2,3,206435,07-08-2023,3337,Pending,Returned,Wallet,Express,SID-pLSPerhIwUJK
3,4,144974,2025-01-07,6461,Pending,In Transit,Credit Card,Standard,SID-kaSlsJ6bOcWw
4,5,122490,19/03/2023,2225,Delivered,Returned,Cash on Delivery,Standard,SID-WYTDRjxticd8

In [3]:
df.shape

(52918, 9)

In [4]:
df.columns

Index(['order_id', 'customer_id', 'order_date', 'warehouse_id', 'order_status',
       'shipment_status', 'payment_method', 'shipping_mode', 'session_id'],
      dtype='object')

### Data Cleaning

#### Checking Missing Values

In [5]:
df.isnull().sum()  #0.9%

order_id             0
customer_id          0
order_date           0
warehouse_id         0
order_status       517
shipment_status      0
payment_method       0
shipping_mode        0
session_id           0
dtype: int64

#### Handling Missing Values

In [6]:
df['order_status'] = df['order_status'].str.strip().replace('', np.nan)

In [7]:
df['order_status'].value_counts()

order_status
Cancelled     8806
Returned      8773
Shipped       8733
Pending       8723
Processing    8690
Delivered     8663
Name: count, dtype: int64

In [8]:
a = ['Cancelled','Returned','Shipped']
df['order_status'] = df['order_status'].apply(lambda x: np.random.choice(a) if pd.isna(x) else x)

#### Detecting Extra Spaces

In [9]:
x = ['order_status', 'shipment_status', 'payment_method', 'shipping_mode']
for i in x:
    print(df[i].unique())

['Processing' 'Delivered' 'Pending' 'Returned' 'Cancelled' 'Shipped']
['Returned' 'Not Shipped' 'In Transit' 'Packed' 'Delivered']
['UPI' 'Credit Card' 'Wallet' 'Cash on Delivery' 'Debit Card'
 'Net Banking']
['Same Day' 'Express' 'Standard' 'Next Day']

In [10]:
df = df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

#### Checking Duplicates

In [11]:
df.duplicated().sum()

np.int64(10)

#### Handling Duplicates

In [12]:
df = df.drop_duplicates()

#### Checking Data Types

In [13]:
df.dtypes

order_id            int64
customer_id         int64
order_date         object
warehouse_id        int64
order_status       object
shipment_status    object
payment_method     object
shipping_mode      object
session_id         object
dtype: object

#### Converting Data Types

In [14]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed')

In [15]:
df.dtypes

order_id                    int64
customer_id                 int64
order_date         datetime64[ns]
warehouse_id                int64
order_status               object
shipment_status            object
payment_method             object
shipping_mode              object
session_id                 object
dtype: object

#### Removing Irrelevent Column

In [16]:
df.drop(columns='session_id',inplace=True)

In [17]:
df.head()

,order_id,customer_id,order_date,warehouse_id,order_status,shipment_status,payment_method,shipping_mode
0,1,120024,2024-02-14,8450,Processing,Returned,UPI,Same Day
1,2,204325,2024-12-23,7713,Delivered,Not Shipped,Credit Card,Express
2,3,206435,2023-07-08,3337,Pending,Returned,Wallet,Express
3,4,144974,2025-01-07,6461,Pending,In Transit,Credit Card,Standard
4,5,122490,2023-03-19,2225,Delivered,Returned,Cash on Delivery,Standard

#### Saving Cleaned Dataset

In [18]:
df.to_csv('Orders_Clean.csv', index=False)