In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Suppliers_v2.csv')
df.head()

,supplier_id,supplier_name,city,country,supplier_type,lead_time,rating,legacy_supplier_code
0,1,Blue Supply 1,Miami,China,Wholesaler,9,3.1,LSC-0Y6DPBHS
1,2,Global Partners 2,Seattle,Mexico,Wholesaler,24,4.1,LSC-THV3A3ZM
2,3,Summit Trading 3,San Francisco,Mexico,Wholesaler,5,2.7,LSC-D4V30T9N
3,4,Evergreen Enterprises 4,Denver,China,Manufacturer,20,3.0,LSC-CX1945NQ
4,5,Rapid Wholesale 5,Denver,Vietnam,Manufacturer,13,3.0,LSC-J7XVG0FN

In [3]:
df.shape

(10387, 8)

In [4]:
df.isnull().sum()    #4%

supplier_id               0
supplier_name             0
city                      0
country                   0
supplier_type             0
lead_time                 0
rating                  518
legacy_supplier_code      0
dtype: int64

In [5]:
df['rating'] = df['rating'].fillna(df.groupby('supplier_type')
    ['rating'].transform(lambda x:x.mode().iloc[0] if not x.mode().empty else np.nan))

In [6]:
df.duplicated().sum()

np.int64(7)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
a = ['city','country','supplier_type']
for i in a:
    print(df[i].value_counts())

city
Philadelphia     571
Charlotte        557
Miami            550
Austin           537
Boston           537
Portland         537
Atlanta          532
Los Angeles      517
Denver           515
San Jose         515
New York         514
Phoenix          511
Dallas           508
Columbus         500
Nashville        498
Detroit          497
Seattle          496
Chicago          488
San Francisco    485
Houston          440
PHOENIX           14
Phoenix           10
CHICAGO            7
New york           6
chicago            6
 Los Angeles       6
Los angeles        5
HOUSTON            4
 Houston           4
NEW YORK           4
 new york          3
Chicago            3
LOS ANGELES        3
Name: count, dtype: int64
country
Japan          1081
India          1063
China          1048
Mexico         1047
Germany        1033
Thailand       1031
South Korea    1030
Vietnam        1025
USA            1012
Canada         1010
Name: count, dtype: int64
supplier_type
Distributor     3517
Wholesaler      3461
Manufacturer    3402
Name: count, dtype: int64

In [9]:
df['city'] = df['city'].str.title().str.strip()

In [10]:
df['city'].value_counts()

city
Philadelphia     571
Charlotte        557
Miami            550
Austin           537
Portland         537
Boston           537
Phoenix          535
Atlanta          532
Los Angeles      531
New York         527
Denver           515
San Jose         515
Dallas           508
Chicago          504
Columbus         500
Nashville        498
Detroit          497
Seattle          496
San Francisco    485
Houston          448
Name: count, dtype: int64

In [11]:
df.drop(columns=['legacy_supplier_code'],inplace=True)

In [12]:
df.head()

,supplier_id,supplier_name,city,country,supplier_type,lead_time,rating
0,1,Blue Supply 1,Miami,China,Wholesaler,9,3.1
1,2,Global Partners 2,Seattle,Mexico,Wholesaler,24,4.1
2,3,Summit Trading 3,San Francisco,Mexico,Wholesaler,5,2.7
3,4,Evergreen Enterprises 4,Denver,China,Manufacturer,20,3.0
4,5,Rapid Wholesale 5,Denver,Vietnam,Manufacturer,13,3.0

In [13]:
a=df[['lead_time','rating']].describe(percentiles=[0.01,0.02,0.05,0.95,0.97,0.98,0.99]).T
a=a.iloc[:,3:]
a

            min   1%   2%   5%   50%   95%   97%     98%   99%   max
lead_time -20.0  2.0  2.0  3.0  16.0  29.0  30.0  30.000  30.0  30.0
rating     -1.0  2.5  2.5  2.6   3.7   4.9   4.9   4.942   5.0   6.5

In [14]:
df['lead_time'] = np.where(df['lead_time']<df['lead_time'].quantile(0.01),
                           df['lead_time'].quantile(0.01),df['lead_time'])

In [15]:
df['rating'] = np.where(df['rating']<0,0,df['rating'])

In [16]:
df[['rating','lead_time']] = df[['rating','lead_time']].round(1)

In [18]:
df.to_csv('Supplier.csv',index=False)